# Runs tests on any push or pull request.
# If the tests pass and this is a push to the main branch also run Semantic Release.
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: Test (Node v${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm test
        run: |
          npm ci
          npm test
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: git config
        shell: bash
        env:
          BOT_USER_NAME: ${{ vars.BOT_USER_NAME }}
          BOT_USER_ID: ${{ vars.BOT_USER_ID }}
          BOT_PUBLIC_KEY: ${{ vars.BOT_PUBLIC_KEY }}
          BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          install -m 600 <(echo "$BOT_PUBLIC_KEY") ~/.ssh/git.pub
          install -m 600 <(echo "$BOT_PRIVATE_KEY") ~/.ssh/git
          eval `ssh-agent -s`
          ssh-add ~/.ssh/git
          git config user.name "${BOT_USER_NAME}"
          git config user.email "${BOT_USER_ID}+${BOT_USER_NAME}@users.noreply.github.com"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/git.pub
          git config --global commit.gpgsign true
      - uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
