# Run `npm run fix` on any push or pull request.
# If changes were made and the tests pass, commit the changes back.
name: Fix
on: [push, pull_request, workflow_dispatch]
jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: git config
        shell: bash
        env:
          BOT_USER_NAME: ${{ vars.BOT_USER_NAME }}
          BOT_USER_ID: ${{ vars.BOT_USER_ID }}
          BOT_PUBLIC_KEY: ${{ vars.BOT_PUBLIC_KEY }}
          BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          install -m 600 <(echo "$BOT_PUBLIC_KEY") ~/.ssh/git.pub
          install -m 600 <(echo "$BOT_PRIVATE_KEY") ~/.ssh/git
          eval `ssh-agent -s`
          ssh-add ~/.ssh/git
          git config user.name "${BOT_USER_NAME}"
          git config user.email "${BOT_USER_ID}+${BOT_USER_NAME}@users.noreply.github.com"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/git.pub
          git config --global commit.gpgsign true
      - name: npm run fix
        shell: bash
        run: |
          npm ci
          npm run fix
          npm run test
          git commit -am "style: npm run fix" && git push || echo "Nothing to commit"
